#!/bin/sh

# Startup Applications

# Launch Polybar
$HOME/.config/polybar/launch.sh &

# run simple X hot key daemon (sxhkd) bind keys
killall sxhkd
sxhkd &

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#Single monitor
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor VGA-0 -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

###---Autostart---###
#xrdb ~/.Xresources &
#killall bspswallow
#pidof bspswallow || bspswallow &

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          20
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4C566A"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#88C0D0"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

###---Rules---###
#--------------------- open applications on specific workspaces -----------------------------------

#bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on 
bspc rule -a Brave-browser desktop='^2' follow=on 
bspc rule -a VSCodium desktop='^3' follow=on
bspc rule -a robo3t desktop='^4' follow=on 
bspc rule -a Postman desktop='^5' follow=on 
bspc rule -a Gimp desktop='^6' follow=on 
bspc rule -a Inkscape desktop='^6' follow=on
bspc rule -a libreoffice-writer desktop='^7' follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a Thunar desktop='^8' follow=on
bspc rule -a Pamac-manager desktop='^9' follow=on
bspc rule -a persepolis desktop='^10'

# fullscreen applications
bspc rule -a Sxiv state=fullscreen
bspc rule -a mpv state=fullscreen





















